# SPDX-FileCopyrightText: Copyright Contributors to the GXF project
#
# SPDX-License-Identifier: Apache-2.0
version: 2
registries:
  maven-artifactory:
    type: maven-repository
    url:  https://maven.pkg.github.com/osgp/
    username: IoTFDP
    password: ${{secrets.IOTFDP_GITHUB_TOKEN}}
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
