// SPDX-FileCopyrightText: Contributors to the GXF project
//
// SPDX-License-Identifier: Apache-2.0

import com.diffplug.gradle.spotless.SpotlessExtension
import com.github.davidmc24.gradle.plugin.avro.GenerateAvroJavaTask
import io.spring.gradle.dependencymanagement.internal.dsl.StandardDependencyManagementExtension
import org.gradle.kotlin.dsl.withType
import org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    alias(libs.plugins.springBoot)
    alias(libs.plugins.dependencyManagement)
    alias(libs.plugins.kotlin)
    alias(libs.plugins.spring)
    alias(libs.plugins.jpa)
    alias(libs.plugins.avro)
    alias(libs.plugins.spotless)
    alias(libs.plugins.sonarqube)
    alias(libs.plugins.eclipse)
    alias(libs.plugins.jacoco)
    alias(libs.plugins.jacocoReportAggregation)
}

group = "org.gxf.template"
version = System.getenv("GITHUB_REF_NAME")?.replace("/", "-")?.lowercase() ?: "develop"

sonar {
    properties {
        property("sonar.host.url", "https://sonarcloud.io")
        property("sonar.projectKey", "OSGP_gxf-service-template")
        property("sonar.organization", "gxf")
    }
}

dependencies {
    implementation(libs.springBootStarterActuator)
    implementation(libs.springBootStarterWeb)
    implementation(libs.springBootAutoconfigure)

    implementation(libs.springAop)
    implementation(libs.springBootStarterKafka)
    implementation(libs.springIntegrationMqtt)

    implementation(libs.logging)

    implementation(libs.mqttclient)

    api(libs.avro)

    implementation(libs.kafkaAvro)
    implementation(libs.kafkaAzureOAuth)

    implementation(libs.springAspects)

    runtimeOnly(libs.micrometerPrometheusModule)

    testImplementation(libs.springBootStarterTest)

    testImplementation(libs.junitJupiterApi)
    testImplementation(libs.junitJupiterEngine)
    testImplementation(libs.junitJupiterParams)

    // Generate test and integration test reports
    jacocoAggregation(rootProject)
}

repositories {
    mavenCentral()
    maven {
        name = "GXFGithubPackages"
        url = uri("https://maven.pkg.github.com/osgp/*")
        credentials {
            username = project.findProperty("github.username") as String? ?: System.getenv("GITHUB_ACTOR")
            password = project.findProperty("github.token") as String? ?: System.getenv("GITHUB_TOKEN")
        }
    }
}

extensions.configure<SpotlessExtension> {
    kotlin {
        ktlint()
            .editorConfigOverride(
                mapOf("max_line_length" to "120", "ij_kotlin_indent_before_arrow_on_new_line" to true),
            )
        licenseHeaderFile(
            "${project.rootDir}/license-template.kt",
            "package",
        ).updateYearWithLatest(false)

        // Exclude files generated by open api
        targetExclude("build/generated/**")
    }
    kotlinGradle {
        ktlint()
            .editorConfigOverride(
                mapOf("max_line_length" to "120", "ij_kotlin_indent_before_arrow_on_new_line" to true),
            )
    }
}

extensions.configure<StandardDependencyManagementExtension> {
    imports {
        mavenBom(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
    }
}

extensions.configure<KotlinJvmProjectExtension> {
    jvmToolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    compilerOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}

tasks.register<Copy>("updateGitHooks") {
    description = "Copies the pre-commit Git Hook to the .git/hooks folder."
    group = "verification"
    from("${project.rootDir}/scripts/pre-commit")
    into("${project.rootDir}/.git/hooks")
}

tasks.withType<KotlinCompile> {
    dependsOn(
        tasks.withType<GenerateAvroJavaTask>(),
        tasks.named("updateGitHooks"),
    )
}

tasks.withType<org.springframework.boot.gradle.tasks.bundling.BootBuildImage> {
    imageName.set("ghcr.io/osgp/gxf-service-template:$version")
    if (project.hasProperty("publishImage")) {
        publish.set(true)
        docker {
            publishRegistry {
                username.set(System.getenv("GITHUB_ACTOR"))
                password.set(System.getenv("GITHUB_TOKEN"))
            }
        }
    }
}

testing {
    suites {
        val integrationTest by
            registering(JvmTestSuite::class) {
                useJUnitJupiter()
                dependencies {
                    implementation(project())
                    implementation(libs.springBootStarterTest)
                    implementation(libs.springBootStarterKafkaTest)
                    implementation(libs.kafkaTestContainer)
                }
            }
    }
}
