// SPDX-FileCopyrightText: Contributors to the GXF project
//
// SPDX-License-Identifier: Apache-2.0

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This settings file is used to specify which projects to include in your build-logic build.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "gxf-service-template-build-logic"
